### ISSUE TITLE
TypeError: Class constructor LRUCache cannot be invoked without 'new'

### ISSUE THREAD

**Issue by tom-rade** [BenLubar/nodebb-plugin-pwned-passwords#8]
NodeBB version: v1.11.1
NodeBB git hash: 3859d41
Database type: mongo
Database version: v4.0.5
NodeJS version: v8.15.0

```
nodebb_1  | 2019-01-15T22:22:30.310Z [4568/48] - error: TypeError: Class constructor LRUCache cannot be invoked without 'new'
nodebb_1  |     at Object.<anonymous> (/usr/src/app/node_modules/nodebb-plugin-pwned-passwords/library.js:8:15)
nodebb_1  |     at Module._compile (module.js:653:30)
nodebb_1  |     at Object.Module._extensions..js (module.js:664:10)
nodebb_1  |     at Module.load (module.js:566:32)
nodebb_1  |     at tryModuleLoad (module.js:506:12)
nodebb_1  |     at Function.Module._load (module.js:498:3)
nodebb_1  |     at Module.require (module.js:597:17)
nodebb_1  |     at Module.module.require (/usr/src/app/src/plugins/index.js:43:25)
nodebb_1  |     at require (internal/module.js:11:18)
nodebb_1  |     at Object.Plugins.requireLibrary (/usr/src/app/src/plugins/index.js:62:32)
```

**Comment by teotikalki** [comment]
I had the same error. I have since removed the plugin since I never saw any evidinece of it existing outside of those logs.

NodeBB version: v1.10.0
Database type: postgres
NodeJS version: v11.6.0

I was posting about another error and @pitaj said that node11 wasn't fully supported yet; I will take you having the same error in a totally different environment as a sign that neither postgres nor node v11 are the culprits.
